#!/bin/bash
# Specter Signals — Core Scraper
# Uses curl + APIs that work TODAY

DATA_DIR="/home/ubuntu/.openclaw/workspace/projects/specter-signals/data"
OUT_DIR="/home/ubuntu/.openclaw/workspace/projects/specter-signals/digests"
mkdir -p $DATA_DIR $OUT_DIR

TS=$(date -u +"%Y%m%d-%H%M%S")
DATE=$(date -u +"%Y-%m-%d")

echo "[+] Specter Signals Scraper — $DATE"

# 1. Wallet balance
WALLET=$(curl -s -X POST https://mainnet.base.org \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"eth_getBalance","params":["0x889d72eeaa4a9e0f18803d01a1a7a797d5e26ac4","latest"],"id":1}' \
  | grep -o '"result":"[^"]*"' | cut -d'"' -f4)

if [ -n "$WALLET" ]; then
  ETH_BALANCE=$(python3 -c "print(int('$WALLET', 16) / 1e18)")
else
  ETH_BALANCE="unknown"
fi
echo "    [✓] Wallet: $ETH_BALANCE ETH"

# 2. BTC price
BTC=$(curl -s https://api.coinbase.com/v2/prices/BTC-USD/spot 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['data']['amount'])" 2>/dev/null)
echo "    [✓] BTC: $BTC"

# 3. ETH price
ETH=$(curl -s https://api.coinbase.com/v2/prices/ETH-USD/spot 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['data']['amount'])" 2>/dev/null)
echo "    [✓] ETH: $ETH"

# Write data
printf '{"wallet": "%s", "btc": "%s", "eth": "%s", "timestamp": "%s"}\n' "$ETH_BALANCE" "$BTC" "$ETH" "$DATE" > "$DATA_DIR/snapshot-$TS.json"

# Generate digest (using printf to avoid heredoc issues)
printf '# Specter Signals — %s\n\n## Market Snapshot\n- **ETH:** $%s\n- **BTC:** $%s\n- **Specter Wallet:** %s ETH\n\n## Active Opportunities\n- Node Network testnet ends Mar 5\n- Incentiv L1 ongoing\n- Monad points system live\n\n## Actions Today\n- Built Specter Signals infrastructure\n- Launched autonomous alpha tracking\n\n---\n*Generated by Specter | Autonomous Intelligence*\n' "$DATE" "$ETH" "$BTC" "$ETH_BALANCE" > "$OUT_DIR/digest-$DATE.md"

echo "[+] Digest written: $OUT_DIR/digest-$DATE.md"
